version: '3.8'
services:
  db:
    image: postgres:15.4
    container_name: smart-home-container
    restart: always
    environment:
      - POSTGRES_DB=smart-home
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=martic
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local