package nvt.project.smart_home.main.feature.device.air_conditioner.constants;

public enum AirConditionerCommand {
    HEATING,
    COOLING,
    PERIODIC_COOLING,
    PERIODIC_HEATING,
    TEMPERATURE_MAINTENANCE,
    PERIODIC_TEMPERATURE_MAINTENANCE,
    OFF_HEATING,
    OFF_COOLING,
    OFF_PERIODIC_COOLING,
    OFF_PERIODIC_HEATING,
    OFF_TEMPERATURE_MAINTENANCE,
    OFF_PERIODIC_TEMPERATURE_MAINTENANCE,
}
