export enum AirConditionerCommand {
  HEATING = 'HEATING',
  COOLING = 'COOLING',
  PERIODIC_COOLING = 'PERIODIC_COOLING',
  PERIODIC_HEATING = 'PERIODIC_HEATING',
  TEMPERATURE_MAINTENANCE = 'TEMPERATURE_MAINTENANCE',
  PERIODIC_TEMPERATURE_MAINTENANCE = 'PERIODIC_TEMPERATURE_MAINTENANCE',
  OFF_HEATING = 'OFF_HEATING',
  OFF_COOLING = 'OFF_COOLING',
  OFF_PERIODIC_COOLING = 'OFF_PERIODIC_COOLING',
  OFF_PERIODIC_HEATING = 'OFF_PERIODIC_HEATING',
  OFF_TEMPERATURE_MAINTENANCE = 'OFF_TEMPERATURE_MAINTENANCE',
  OFF_PERIODIC_TEMPERATURE_MAINTENANCE = 'OFF_PERIODIC_TEMPERATURE_MAINTENANCE',
}