export enum AirConditionerCurrentWorkMode {
    HEATING = 'HEATING',
    COOLING = 'COOLING',
    TEMPERATURE_MAINTENANCE = 'TEMPERATURE_MAINTENANCE',
    PERIODIC_COOLING = 'PERIODIC_COOLING',
    PERIODIC_HEATING = 'PERIODIC_HEATING',
    PERIODIC_TEMPERATURE_MAINTENANCE = 'PERIODIC_TEMPERATURE_MAINTENANCE',
    OFF = 'OFF',
}